name: nlp_env
channels:
  - conda-forge
dependencies:
  # Core Python and scientific stack
  - python=3.10
  - numpy=1.26.4
  - pandas=1.5.3
  - scikit-learn=1.3.0
  - matplotlib=3.7.0
  - seaborn=0.12.2
  - tqdm=4.65.0
  - wordcloud=1.9.3

  # spaCy + compatible dependencies
  - spacy=3.6.1
  - thinc=8.1.10

  # Transformers + tokenizers (from conda-forge → prebuilt binaries)
  - tokenizers=0.19.1
  - transformers=4.42.4
  - datasets=2.18.0

  # Jupyter + kernel
  - jupyterlab=4.0.0
  - ipykernel
  

  # Pip for pure-Python packages
  - pip
  - pip:
      # SciSpaCy (installed with --no-deps to avoid spaCy rebuilds)
      - scispacy==0.5.3
      # Optional: SciSpaCy model (small)
      # - https://github.com/allenai/scispacy-models/releases/download/v0.5.3/en_core_sci_sm-0.5.3.tar.gz

